### ISSUE TITLE
handle stream recording

### ISSUE THREAD

**Issue by dedalusmax** [dedalusmax/LiveChefService#7]
DEMO:
https://webrtc.github.io/samples/src/content/getusermedia/record/

code:
https://github.com/webrtc/samples/tree/gh-pages/src/content/getusermedia/record

**Comment by dedalusmax** [comment]
pseudo-code:
`
var mediaSource = new MediaSource();
mediaSource.addEventListener('sourceopen', handleSourceOpen, false);

var recordedVideo = document.querySelector('video#recorded');
var mediaRecorder;
var recordedBlobs;
var sourceBuffer;

`

getusermedia....

`
function startRecording() {
  recordedBlobs = [];
  var options = {mimeType: 'video/webm;codecs=vp9'};
  if (!MediaRecorder.isTypeSupported(options.mimeType)) {
    console.log(options.mimeType + ' is not Supported');
    options = {mimeType: 'video/webm;codecs=vp8'};
    if (!MediaRecorder.isTypeSupported(options.mimeType)) {
      console.log(options.mimeType + ' is not Supported');
      options = {mimeType: 'video/webm'};
      if (!MediaRecorder.isTypeSupported(options.mimeType)) {
        console.log(options.mimeType + ' is not Supported');
        options = {mimeType: ''};
      }
    }
  }
  try {
    mediaRecorder = new MediaRecorder(window.stream, options);
  } catch (e) {
    console.error('Exception while creating MediaRecorder: ' + e);
    alert('Exception while creating MediaRecorder: '
      + e + '. mimeType: ' + options.mimeType);
    return;
  }
  console.log('Created MediaRecorder', mediaRecorder, 'with options', options);
  recordButton.textContent = 'Stop Recording';
  playButton.disabled = true;
  downloadButton.disabled = true;
  mediaRecorder.onstop = handleStop;
  mediaRecorder.ondataavailable = handleDataAvailable;
  mediaRecorder.start(10); // collect 10ms of data
  console.log('MediaRecorder started', mediaRecorder);
}

function stopRecording() {
  mediaRecorder.stop();
  console.log('Recorded Blobs: ', recordedBlobs);
  recordedVideo.controls = true;
}

function play() {
  var superBuffer = new Blob(recordedBlobs, {type: 'video/webm'});
  recordedVideo.src = window.URL.createObjectURL(superBuffer);
}

function download() {
  var blob = new Blob(recordedBlobs, {type: 'video/webm'});
  var url = window.URL.createObjectURL(blob);
  var a = document.createElement('a');
  a.style.display = 'none';
  a.href = url;
  a.download = 'test.webm';
  document.body.appendChild(a);
  a.click();
  setTimeout(function() {
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  }, 100);
}
`

**Comment by anabellikeckes** [comment]
**Experimental Web Platform features** --> enable flag in - chrome://flags/

**Comment by anabellikeckes** [comment]
```
 <div class="col-sm-4">
   <h4>Record options</h4>
<button class="btn btn-primary" id="record" data-bind="click: toggleRecording">Start recording</button>
<button class="btn btn-default" id="play" data-bind="click: play">Play</button>
<button class="btn btn-default" id="download" data-bind="click: download">Download</button>
</div>

 <video id="recorded" autoplay loop></video>
```
variables: 

```
 self.mediaRecorder;
 self.recordedBlobs = [];
self.recordedVideo = null;
 self.recordButton = null;
 self.playButton = null;
 self.downloadButton = null;
 var mediaSource = new MediaSource();
 mediaSource.addEventListener('sourceopen', self.handleSourceOpen, false);
```
in method startBroadcast:

```
self.recordButton = document.querySelector('#record');
self.playButton = document.querySelector('#play');
self.downloadButton = document.querySelector('#download');
```
buttons methods: 

```
self.toggleRecording = function () {

        self.recordedVideo = document.querySelector('#recorded');
        if (self.recordButton.textContent == 'Start recording') {
            self.createMediaRecorder();
            self.startRecording();
        } else {
            self.stopRecording();
            self.recordButton.textContent = 'Start recording';
            // playButton.disabled = false;
            // downloadButton.disabled = false;
        }
    };

    self.play = function () {
        var superBuffer = new Blob(self.recordedBlobs, { type: 'video/webm' });
        self.recordedVideo.src = window.URL.createObjectURL(superBuffer);
    };

    self.download = function () {
        var blob = new Blob(self.recordedBlobs, { type: 'video/webm' });
        var url = window.URL.createObjectURL(blob);
        var a = document.createElement('a');
        a.style.display = 'none';
        a.href = url;
        a.download = 'chefRecord.webm';
        document.body.appendChild(a);
        a.click();
        setTimeout(function () {
            document.body.removeChild(a);
            window.URL.revokeObjectURL(url);
        }, 100);
    }

    self.handleSourceOpen = function () {
        console.log('MediaSource opened');
        self.sourceBuffer = mediaSource.addSourceBuffer('video/webm; codecs="vp8"');
        console.log('Source buffer: ', self.sourceBuffer);
    }
```
methods:

```
CookingPresenterViewModel.prototype.createMediaRecorder = function () {


    var self = this;

    var communicator = root.main().communicator;

    self.recordedBlobs = [];
    var options = { mimeType: 'video/webm;codecs=vp9' };
    if (!MediaRecorder.isTypeSupported(options.mimeType)) {
        console.log(options.mimeType + ' is not Supported');
        options = { mimeType: 'video/webm;codecs=vp8' };
        if (!MediaRecorder.isTypeSupported(options.mimeType)) {
            console.log(options.mimeType + ' is not Supported');
            options = { mimeType: 'video/webm' };
            if (!MediaRecorder.isTypeSupported(options.mimeType)) {
                console.log(options.mimeType + ' is not Supported');
                options = { mimeType: '' };
            }
        }
    }
    try {
        self.mediaRecorder = new MediaRecorder(communicator.localStream, options);
    } catch (e) {
        console.error('Exception while creating MediaRecorder: ' + e);
        alert('Exception while creating MediaRecorder: '
            + e + '. mimeType: ' + options.mimeType);
        return;
    }
    console.log('Created MediaRecorder', self.mediaRecorder, 'with options', options);
    self.recordButton.textContent = 'Stop Recording';

    //playButton.disabled = true;
    //downloadButton.disabled = true;
}

CookingPresenterViewModel.prototype.startRecording = function () {

    var self = this;

    self.mediaRecorder.start(10); // collect 10ms of data
    console.log('MediaRecorder started', self.mediaRecorder);
    self.mediaRecorder.onstop = self.handleStop;
    self.mediaRecorder.ondataavailable = self.handleDataAvailable;


    self.handleDataAvailable = function (event) {
        var self = this;
        var recordedBlobs = [];
        if (event.data) {
            recordedBlobs.push(event.data);
        }
        self.recordedBlobs = recordedBlobs;

        console.log('Recorded Blobs: ', self.recordedBlobs);
    }
};

CookingPresenterViewModel.prototype.stopRecording = function () {

    var self = this;
    self.mediaRecorder.stop();
    console.log('Recorded Blobs: ', self.recordedBlobs);
    self.recordedVideo.controls = true;
}

CookingPresenterViewModel.prototype.handleStop = function (event) {
    console.log('Recorder stopped: ', event);
}

```

issues:

- after second time I click "Start recording"  **self.mediaRecorder.ondataavailable** method triggers
- problem with **self** in **self.recordedBlobs**
